[package]
name = "snes_address"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/smedit/snes_address/"
description = "A library for translating memory address for SNES games"
license = "MIT"

[dependencies]
thiserror = "1.*"

